_wandb:
    value:
        cli_version: 0.26.1
        e:
            od5zl407zs371pq29rg0hwb4hloojnji:
                args:
                    - --data-path
                    - /home/nam_ngothanh05/gcs_mount/imagenet-latent-vae-encode/train-*.ar
                    - --val-data-path
                    - /home/nam_ngothanh05/gcs_mount/imagenet-latent-vae-encode/val-*.ar
                    - --model-size
                    - XL
                    - --batch-size
                    - "256"
                    - --epochs
                    - "1000"
                    - --steps-per-epoch
                    - "5000"
                    - --learning-rate
                    - "1e-4"
                    - --ema-decay
                    - "0.9999"
                    - --grad-clip
                    - "1.0"
                    - --cfg-prob
                    - "0.1"
                    - --sample-cfg-scale
                    - "1.0"
                    - --vae-model
                    - /home/nam_ngothanh05/models/vae
                    - --inception-score-weights
                    - /home/nam_ngothanh05/models/inception/inception_v3_google-0cc3c7bd.pth
                    - --ckpt-dir
                    - /home/nam_ngothanh05/checkpoints/sit-xl
                    - --ckpt-freq
                    - "5000"
                    - --ckpt-keep
                    - "1"
                    - --eval-freq
                    - "5000"
                    - --sample-freq
                    - "5000"
                    - --sample-num-steps
                    - "50"
                    - --fid-freq
                    - "50000"
                    - --num-fid-samples
                    - "50000"
                    - --fid-num-steps
                    - "50"
                    - --fid-batch-size
                    - "32"
                    - --inception-score
                    - --precision-recall
                    - --log-freq
                    - "20"
                    - --wandb-project
                    - sit-vanilla-jax
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 120
                cpu_count_logical: 240
                disk:
                    /:
                        total: "103865303040"
                        used: "17345814528"
                email: nam.ngothanh05@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: b7dc197e86c29e70c445023da44c7982d7d779e4
                    remote: https://github.com/Namtk214/SRA.git
                host: t1v-n-439aae19-w-0
                memory:
                    total: "430004359168"
                os: Linux-5.19.0-1022-gcp-x86_64-with-glibc2.35
                program: /home/nam_ngothanh05/SRA/train.py
                python: CPython 3.10.12
                root: /home/nam_ngothanh05/SRA
                startedAt: "2026-05-12T14:05:57.133495Z"
                writerId: od5zl407zs371pq29rg0hwb4hloojnji
        m:
            - "1": train/step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 12
                - 45
                - 49
                - 83
            "2":
                - 1
                - 12
                - 45
                - 49
                - 83
            "3":
                - 7
                - 16
            "4": 3.10.12
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
batch_size:
    value: 256
block_corr_batches:
    value: 2
block_corr_freq:
    value: 0
cfg_prob:
    value: 0.1
ckpt_dir:
    value: /home/nam_ngothanh05/checkpoints/sit-xl
ckpt_freq:
    value: 5000
ckpt_keep:
    value: 1
data_path:
    value: /home/nam_ngothanh05/gcs_mount/imagenet-latent-vae-encode/train-*.ar
ema_decay:
    value: 0.9999
epochs:
    value: 1000
eval_batches:
    value: 4
eval_freq:
    value: 5000
fid_batch_size:
    value: 32
fid_cfg_scale:
    value: 1
fid_eval_local_batch:
    value: 4
fid_freq:
    value: 50000
fid_num_steps:
    value: 50
grad_accum_steps:
    value: 1
grad_clip:
    value: 1
inception_score:
    value: true
inception_score_splits:
    value: 10
inception_score_weights:
    value: /home/nam_ngothanh05/models/inception/inception_v3_google-0cc3c7bd.pth
learning_rate:
    value: 0.0001
linear_probe:
    value: false
log_freq:
    value: 20
mock_data:
    value: false
model_size:
    value: XL
no_wandb:
    value: false
num_fid_samples:
    value: 50000
pr_full_mode:
    value: false
pr_k:
    value: 3
pr_max_samples:
    value: 5000
precision_recall:
    value: true
preflight_checks:
    value: false
preflight_fid_memory_probe:
    value: false
preflight_fid_samples:
    value: 16
preflight_only:
    value: false
preflight_sample_count:
    value: 4
probe_eval_batches:
    value: 4
probe_layer:
    value: null
probe_save_path:
    value: null
resume:
    value: false
sample_cfg_scale:
    value: 1
sample_freq:
    value: 5000
sample_num_steps:
    value: 50
steps_per_epoch:
    value: 5000
vae_decode_batch_size:
    value: 8
vae_hf_config:
    value: /kaggle/working/huggingface_cache/hub/models--stabilityai--sd-vae-ft-ema/snapshots/f04b2c4b98319346dad8c65879f680b1997b204a/config.json
vae_model:
    value: /home/nam_ngothanh05/models/vae
val_data_path:
    value: /home/nam_ngothanh05/gcs_mount/imagenet-latent-vae-encode/val-*.ar
wandb_project:
    value: sit-vanilla-jax
